---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - pre1:
      value: "/Service/Provisioning/StateMachines/Methods/DialogParser"
  - pre2:
      value: "/Service/Provisioning/MultiStage/StateMachines/ServiceProvision_Intermediate/stage_1"
